### ISSUE TITLE
HTTPSession issue

### ISSUE THREAD

**Issue by jflefebvre06** [GoogleCloudPlatform/jetty-runtime#161] opened 2017-05-05 08:29 UTC
Hello,

I have write the very simple servlet bellow :
```
@WebServlet(name = "index", value = "")
public class IndexServlet extends HttpServlet {
	@Override
	public void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
		final PrintWriter out = resp.getWriter();
		HttpSession session= req.getSession(true);
		out.println("Session id : " + session.getId());
		out.println("Session new : " + session.isNew());
		AtomicInteger ato=(AtomicInteger) session.getAttribute("ATO");		
		if(ato==null){			
			out.println("ato null");
			ato= new AtomicInteger();
		}else{
			out.println("ato before " + ato.get());	
		}
		ato.incrementAndGet();
		session.setAttribute("ATO", ato);
		out.println("ato after " + ((AtomicInteger) session.getAttribute("ATO")).get());	
	}
}
```

The servet create a new session if not exist and put an incremental integer.

The servlet is deployed into flexible environmment (2 instances) :
```
# [START runtime]
runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling:
  instances: 2
# [END runtime]
```

When I browse my servlet, and I refresh the page,  I can see that the session id change :
Session id **node05amknapl2nae1w36p9h06jc4413**
Session new true

Session id **node0k5vvl8mqww941bw2mmrsinaun7**
Session new true

I understand it is because nginx sticky session future is not configured.

What can I do to share HttpSession between my 2 instances ?

Thanks

**Comment by aslo** [comment] 2017-05-05 16:34
Hi @jflefebvre06, 

Since there's currently no sticky sessions in App Engine Flexible, sessions would need to be persisted using a storage mechanism that's visible to all instances running your application. We are currently working on supporting that feature out-of-the-box in the jetty runtime using Google Cloud Datastore - see #41 for more detail. Unfortunately, until that time, you would need to manually handle session persistence.

@meltsufin or @janbartel may have more info.

**Comment by jflefebvre06** [comment] 2017-05-09 07:47
Hi @aslo 

I have try to use "session-store-gcloud" but it is not seems to work very well.

My dockerfile :
```
FROM gcr.io/google-appengine/jetty
ADD test-0.0.1-SNAPSHOT.war $JETTY_BASE/webapps/root.war
WORKDIR $JETTY_BASE
RUN java -jar $JETTY_HOME/start.jar --approve-all-licenses --add-to-start=slf4j-jul,session-store-gcloud
```

My app.yaml :
```
# [START runtime]
runtime: custom
env: flex

service: test

handlers:
- url: /.*
  script: this field is required, but ignored

resources:
  cpu: 1
  memory_gb: 0.6

health_check:
  enable_health_check: False

manual_scaling:
  instances: 2

# [END runtime]
```

Anything else to do ?

**Comment by janbartel** [comment] 2017-05-09 08:43
@jflefebvre06 I've deployed a simple test app using your app.yaml and Dockerfile and it seems to be working fine so far, but I need to test with a few more instances. While I get that underway, can you be more specific about what is not working?

@aslo can you confirm that the environment variable GAE_MODULE_INSTANCE is being set in the flex environment?  Jetty uses this to determine a unique name for each server/session id manager instance. If this is not unique then I can image there would be problems, and this is perhaps what @jflefebvre06 is experiencing, although will need a description from him of the exact problem to confirm.

**Comment by jflefebvre06** [comment] 2017-05-09 08:48
Hi @janbartel 

Could you please use my servlet :
```
@WebServlet(name = "index", value = "")
public class IndexServlet extends HttpServlet {
	@Override
	public void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
		final PrintWriter out = resp.getWriter();
		HttpSession session= req.getSession(true);
		out.println("Session id : " + session.getId());
		out.println("Session new : " + session.isNew());
		AtomicInteger ato=(AtomicInteger) session.getAttribute("ATO");		
		if(ato==null){			
			out.println("ato null");
			ato= new AtomicInteger();
		}else{
			out.println("ato before " + ato.get());	
		}
		ato.incrementAndGet();
		session.setAttribute("ATO", ato);
		out.println("ato after " + ((AtomicInteger) session.getAttribute("ATO")).get());	
	}
}
```

If you refresh your browser  (simple F5) multiple times, you will see that gap of "ato" is not 1

**Comment by janbartel** [comment] 2017-05-09 09:02
@jflefebvre06 ok I see what the problem is now. This is caused by the fact that by default jetty will use an in-memory session cache. This is exactly what you want when there is a sticky load balancer, but when there's not, it will cause problems. 

Try modifying your docker file to insert "session-cache-null" before "session-store-gcloud" in your RUN line.

**Comment by jflefebvre06** [comment] 2017-05-09 09:20
@janbartel il seems to work very well, thanks a lot !!!!

On the datastore web page (google cloud console) I can see my session but it is no indexes, is it normal ?
![sans titre 1](https://cloud.githubusercontent.com/assets/2685607/25843999/6f2f73fe-34a9-11e7-99b0-592432792ccb.png)

**Comment by janbartel** [comment] 2017-05-09 09:35
@jflefebvre06 I believe gcloud datastore will do some automatic indexing.  Indexing cannot be done programmatically last time I checked. Jetty does provide an index file that you can manually upload using the gcloud SDK. I'll attach it here. If you use this composite index, the session stuff will be a bit faster, but also works without it, just less efficiently.
[index.yaml.gz](https://github.com/GoogleCloudPlatform/jetty-runtime/files/986167/index.yaml.gz)

**Comment by jflefebvre06** [comment] 2017-05-09 09:54
OK thanks a lot

**Comment by jflefebvre06** [comment] 2017-05-10 09:15
Hi @janbartel 

After any tests, the only cases  I found which don't work are :
```
synchronized (request.getSession().getId().intern()) {
    // UPDATE collections stored in session
}
```
Is is due to sticky sessions is not available.

@janbartel , @aslo , any idea resolve that cases ?

**Comment by janbartel** [comment] 2017-05-10 09:56
@jflefebvre06 the http session api isn't transactional, and isn't ideal for data that is often modified, particularly so in clustered situations. So I would suggest you don't store data that you often modify in a session. Instead just use the session id as the key in some clustered storage mechanism that supports transactionality. Have a look at using gcloud datastore directly in your code, as I think it supports transactions.

**Comment by jflefebvre06** [comment] 2017-05-10 10:14
@janbartel in my final code, I have not this case. I have juste wrote it for test.
My problem is that many frameworks use this patterns like Struts, Spring, ...

**Comment by gregw** [comment] 2017-05-10 11:40
@jflefebvre06 can you describe in more detail the tests that are failing for you and how they are failing?

Is the modified collection set again as a session attribute after the modification, ie is there any indication to the session that it is dirty and needs to be written again?   I think you will find that most frameworks that do modify such collections probably also set some other attribute on the session to mark it as dirty.

**Comment by joakime** [comment] 2019-04-30 16:05
The dependent issue #41 was closed in Jul 5, 2017, can this be closed?

**Closed** 2019-05-01 06:12 UTC
