### ISSUE TITLE
GZIP support

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#146] opened 2017-03-31 17:48 UTC
@gregw @jmcc0nn3ll 
How can we enable support for gzip content responses?
Should we enable the [jetty gzip handler](http://www.eclipse.org/jetty/documentation/9.4.x/gzip-filter.html), or are there other options?

**Comment by joakime** [comment] 2017-03-31 20:18
GzipHandler is a great choice.

The default configuration for it is generally a good setup, but there are a few configurables that users might want to control (include/exclude of paths, methods, mime-types, etc)

Even if the user decides to use something that gzip's on its own (like many REST libs) the GzipHandler will detect this situation and not double-compress.

Note: GzipHandler is only for compressing responses.  It has no support for decompressing request content bodies.

**Comment by joakime** [comment] 2017-03-31 20:19
I'm curious, doesn't GFE compress responses already?

**Comment by gregw** [comment] 2017-03-31 22:07
The GzipHandler in jetty now is done below the level of the Response, unlike many previous GzipFilters that used response wrapping.  This allows a very efficient and low impact solution that also works with async IO. It is typically a net improvement for most applications.  We also now support alternate 

Note also that we have a second mechanism in our ResourceService (used by DefaultServlet) that can look for pre-compressed versions of static content and server those instead of compressing on the fly.

We are also increasing our support for brotli compression in these mechanisms, but I don't believe that is 100% coverage yet.

It is a simple module to turn on.

**Comment by meltsufin** [comment] 2017-03-31 23:07
@joakime I'm trying to find out if GFE compresses responses.

@gregw Are there any potential cons to turning on the module? Is it big?

**Comment by gregw** [comment] 2017-03-31 23:14
The module is not big, however the logic needed to decide if a response can be compressed or not is more than trivial and less than onerous.  ie there is some cost to check the headers, the user agent, how the response is being generated etc.      It is also not perfect, specially with regards to faulty clients that have been widely deployed (but are now slowly retiring), so there may be false negatives (not compressing when we could) and even some false positives (compressing when we should not have).

We have many big sites that turn it on routinely.  It is not entirely problem free and we occasionally have to field questions about false positive/negatives.   So the biggest con I see is probably the need to deal with a small increase in support requests.

**Comment by meltsufin** [comment] 2017-03-31 23:24
Is it possible to include the module, but turn it on via an environment variable?

**Comment by gregw** [comment] 2017-04-01 03:40
Certainly.   But as previously said, I think we have to be very cautious about adhoc adding of such variables for all these options.

At the very least, we need to write up a a policy of naming of such env variables (GAE_? GCP_? flex etc.)

Also, rather than creating custom env variables for every module that we may or may not want to configure in jetty, perhaps it is better to have single env variable that can be used to enable modules at runtime.  Something like `GCP_JETTY_ADD_MODULE=gzip`

**Comment by meltsufin** [comment] 2017-04-03 21:32
@gregw Is there a standard way of disabling a Jetty module at startup without actually deleting it from jetty base?  How would an environment variable be used to disable a module?

I agree that using env variables for this is not ideal. It would be an interesting alternative to allow developers to just drop a "jetty.properties" or "jetty.commands" file into the root of application classpath, and have the runtime apply those configurations at startup.

**Comment by gregw** [comment] 2017-04-04 21:30
We don't have a standard way of disabling, but we have set up systems
before that move ini files to a disabled directory.  However i don't think
that helps much.  We already support command line, property files, ini
files and command file as ways to enable. Adding disable or move to enable
does add much semantic.

The problem is how best to communicate desired configuration from dev env
to deployed image when all we have available is the war file and env
variables.

Perhaps we should look for a WEB-INF/jetty.commands and/or a
WEB-INF/setup-env.bash at startup?

The problem with anything in the war is that bakes in one deployment
configuration to a war that may be deployed in multiple environment.

Env vars work but are a bit clunky and need to be well designed.

We need to think how we generally want to mix in deployment configurations
on top of application configuration for all google images.  If it is to be
env vars set in an app.yaml then we just have to make that work for jetty.
  If it is decided that it is OK to mix in deployment configuration with
the application, then it can be a little easier for users as they can pass
specific configuration files eg. logging.properties, jetty.commands,
setup-env.bash etc.  at the cost of the need to repackage for each
deployment environment.  Could be an OK trade off?

**Comment by meltsufin** [comment] 2017-04-05 16:02
@gregw I think your point about keeping configuration in the environment rather than the app is key. It is one of the principles of 12 factor apps, and we need to support it.

Environment variables is the natural way to accomplish it. I do agree that we need to be careful about the naming conventions of these env variables. We essentially need to support `jetty.commands` through environment variables.
```
JETTY_MODULES_ENABLE=gzip,http-forwarded
JETTY_MODULES_DISABLE=jstl
JETTY_CONFIG_PROPERTIES=jetty.httpConfig.headerCacheSize=512,jetty.httpConfig.sendServerVersion=true
```

If something like this seems acceptable, we can update the design doc.

**Comment by gregw** [comment] 2017-04-06 06:11
@meltsufin 
That looks like a reasonable way to go.   Note that there are two ways we could implement something like that.

We could use those variables to run a configuration pass of `java -jar start.jar` where the results are added to the `start.d` directory and then used by a subsequent run of java -jar start.jar.    PRO: resulting configuration is all in filesystem; CON: two executions of java

Alternately we could just use those variables to add properties and --module args to the command line used to run jetty.  However the disable would have to remove like named files from the `start.d` directory.  PRO: single execution of java ; CONS: mix of file ops and command line; will not expand ini-templates that can provide example configurations.

I'm leaning towards the later one as avoiding slow startup is good.  After https://github.com/GoogleCloudPlatform/openjdk-runtime/pull/73 is merged I'll prepare a PR that does this in a `setup-env.d/40-jetty.bash` file and we can refine from there (and then write the specification:)

**Comment by meltsufin** [comment] 2017-04-06 14:28
@gregw I prefer the second option as well. Fast startup is definitely a priority.

**Closed** 2017-05-15 21:27 UTC
